### ISSUE TITLE
NFTokenOfferAccept

### ISSUE THREAD

**Issue by Mwni** [XRPL-Labs/xrpl-sign-keypairs#1]
The xls-20d standard proposes `NFTokenOfferAccept` but the most recent commit is using `NFTokenAcceptOffer`. Has there been a change to the standard? Is there already a testnet implementation? What is going on

**Comment by WietseWind** [comment]
I don't know, sorry. XRPL Labs doesn't build the XLS20 amendment, nor do we maintain the ripple-binary-codec. We'll have to wait to see what the end result is going to be.
